### ISSUE TITLE
Roadmap of Version 0.6

### ISSUE THREAD

**Issue by membphis** [iresty/apisix#143]
We are collecting new features for apisix version 0.6. If you have any suggestions, please leave a message here.

- [x] support HTTPS: https://github.com/iresty/apisix/pull/152
- [x] support for custom certificates for HTTPS: https://github.com/iresty/apisix/pull/152
- [x] add one more port for admin API: https://github.com/iresty/apisix/pull/194
- [x] health check and circuit-breaker
- [x] dashboard: https://github.com/iresty/apisix/pull/170
- [x]  opentracing, implemnt Zipkin first: https://github.com/iresty/apisix/issues/204

**Comment by moonming** [comment]
I think we should add a port for admin API. 
We only have only one port for both proxy and admin APIs, which is hard for ACL.

**Comment by ygm521** [comment]
可增加需求如下：
1，可以通过web页面查看有哪些vser和应用池，以及动态增删虚拟服务和应用池中真实服务器。
2，可以对不同的真实服务器设置不同的健康检查。
3，监控本机的cpu 内存 磁盘使用情况 服务情况 完成ha主备切换。
4,   web页面方式能配置不同协议 https 证书等。
5,   http缓存 压缩 请求响应报文修改 参数调整等。

**Comment by membphis** [comment]
> 可增加需求如下：
> 1，可以通过web页面查看有哪些vser和应用池，以及动态增删虚拟服务和应用池中真实服务器。
需要现有 dashboard 才能开始，然后再开始。

> 2，可以对不同的真实服务器设置不同的健康检查。
刚需功能之一，未来肯定要做。

> 3，监控本机的cpu 内存 磁盘使用情况 服务情况 完成ha主备切换。
这块应该有更专业的第三方，暂不考虑。我们选型 etcd 很大一部分原因就是他对 HA 的支持更完备。

> 4, web页面方式能配置不同协议 https 证书等。
目前 admin API 已经支持，dashboard 正在 review ，希望能赶上 0.6 的版本。

> 5, http缓存 压缩 请求响应报文修改 参数调整等。
