### ISSUE TITLE
roadmap: version 0.8

### ISSUE THREAD

**Issue by membphis** [iresty/apisix#495]
- [x] load routes from local yaml file

- [x] global rules: https://github.com/iresty/apisix/pull/492

- [ ] plugin: cluster limit rate: will implement it later.

- [x] tcp/udp proxy: https://github.com/iresty/apisix/commit/4aaaf3ee5a8df7300ac1c87e4a962cd2117c669e

- [x] MQTT dynamic proxy: https://github.com/iresty/apisix/pull/513

- [x] support to use domain in upstream: https://github.com/iresty/apisix/pull/522

- [x] more doc about APISIX [WIP]: https://github.com/iresty/apisix/pull/531

**Comment by soulsoul** [comment]
more doc about APISIX ， i can do

**Comment by membphis** [comment]
> more doc about APISIX ， i can do

do you have any plan?
